### WINDOWS AND WORKSPACES ###
##############################

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule {
    name = float-center-rule
    match:float = true
    float = on
    size = 500 300
    center = on
}

windowrule {
    name = pavucontrol-float
    match:class = org.pulseaudio.pavucontrol
    float = on
    size = 600 300
    center = on
}

windowrule {
    name = pavucontrol-float
    match:class = org.gnome.Nautilus
    float = on
    size = 1000 700
    center = on
}

windowrule {
    name = btop-float 
    match:class = org.gnome.Nautilus
    float = on
    size = 1000 700
    center = on
}
