[general]
live_config_reload = true # Enable live config reloading
import = ["~/.config/alacritty/colors.toml"]

# Window settings
[window]
dimensions = { columns = 80, lines = 24 } # Default window size
padding = { x = 15, y = 15 } # Padding around the terminal content
decorations = "full" # Window decorations (e.g., title bar, close buttons)
opacity = 0.8 # Window opacity (0.0 - 1.0)

# Font settings
[font]
size = 14.0

[font.normal]
family = "SFMono Nerd Font"
style = "Regular"

[font.bold]
family = "SFMono Nerd Font"
style = "Bold"

[font.italic]
family = "SFMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "SFMono Nerd Font"
style = "Bold Italic"

# Color settings
[colors.primary]
foreground = "#F8F8F2" # Default text color
background = "#282A36" # Default background color

# Cursor settings
[cursor]
style = { shape = "Block", blinking = "On" } # Cursor shape and blinking behavior
