# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = true

# Overall prompt format
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$line_break\
$character
"""

palette = "catppuccin"

[palettes.catppuccin]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold blue)"

[directory]
style = "bold blue"
truncate_to_repo = true
truncation_length = 3
read_only = " "

[git_branch]
symbol = " "
style = "bold mauve"

[git_status]
style = "bold red"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕"
conflicted = "="
deleted = "✘"
renamed = "»"
modified = "!"
staged = "+"
untracked = "?"
stashed = "$"

[cmd_duration]
min_time = 500
format = "[󰔛 $duration](yellow)"

[fill]
symbol = " "

[nodejs]
symbol = " "
style = "green"

[python]
symbol = " "
style = "yellow"
pyenv_version_name = true

[rust]
symbol = " "
style = "red"

[golang]
symbol = " "
style = "cyan"

[java]
symbol = " "
style = "red"

[c]
symbol = " "
style = "blue"

[cpp]
symbol = " "
style = "blue"

[package]
symbol = " "

[docker_context]
symbol = " "
style = "blue"

[kubernetes]
disabled = false
symbol = "☸ "
style = "cyan"

[aws]
symbol = " "
style = "yellow"

[gcloud]
symbol = " "
style = "blue"

[time]
disabled = false
time_format = "%H:%M"
format = "[󰥔 $time](bold cyan)"

[hostname]
ssh_only = true
style = "green"

[username]
show_always = false
style_user = "green"
style_root = "red"

[memory_usage]
disabled = true

[battery]
disabled = false

[status]
disabled = false
symbol = "✖"

[jobs]
symbol = "✦"

[shell]
disabled = false

[os]
disabled = true
