"$schema" = "https://starship.rs/config-schema.json"

add_newline = false
command_timeout = 2000

# PROMPT
format = '[\[$username@$hostname $directory\]](bold white)$character'

[username]
show_always = true
format = "$user"

[hostname]
ssh_only = false
format = "$hostname"

[directory]
format = "$path"
truncation_length = 1
truncate_to_repo = false
home_symbol = "~"

[character]
success_symbol = "[\\$](bold white)"
error_symbol =  "[\\$](bold red)"
vicmd_symbol =  "[\\$](bold green)"

[git_branch]
disabled = true

[git_status]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[rust]
disabled = true

[golang]
disabled = true

[cmd_duration]
disabled = true

[time]
disabled = true

[package]
disabled = true

[battery]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[os]
disabled = true
