
$image = /home/mohiitp/pix/car.png
$background = rgba(15130bff)

$image = /home/mohiitp/pix/car.png
$error = rgba(ffb4abff)

$image = /home/mohiitp/pix/car.png
$error_container = rgba(93000aff)

$image = /home/mohiitp/pix/car.png
$inverse_on_surface = rgba(333027ff)

$image = /home/mohiitp/pix/car.png
$inverse_primary = rgba(6c5e10ff)

$image = /home/mohiitp/pix/car.png
$inverse_surface = rgba(e8e2d4ff)

$image = /home/mohiitp/pix/car.png
$on_background = rgba(e8e2d4ff)

$image = /home/mohiitp/pix/car.png
$on_error = rgba(690005ff)

$image = /home/mohiitp/pix/car.png
$on_error_container = rgba(ffdad6ff)

$image = /home/mohiitp/pix/car.png
$on_primary = rgba(393000ff)

$image = /home/mohiitp/pix/car.png
$on_primary_container = rgba(f6e388ff)

$image = /home/mohiitp/pix/car.png
$on_primary_fixed = rgba(211b00ff)

$image = /home/mohiitp/pix/car.png
$on_primary_fixed_variant = rgba(524600ff)

$image = /home/mohiitp/pix/car.png
$on_secondary = rgba(363016ff)

$image = /home/mohiitp/pix/car.png
$on_secondary_container = rgba(ede2bcff)

$image = /home/mohiitp/pix/car.png
$on_secondary_fixed = rgba(201c04ff)

$image = /home/mohiitp/pix/car.png
$on_secondary_fixed_variant = rgba(4d472bff)

$image = /home/mohiitp/pix/car.png
$on_surface = rgba(e8e2d4ff)

$image = /home/mohiitp/pix/car.png
$on_surface_variant = rgba(cdc6b4ff)

$image = /home/mohiitp/pix/car.png
$on_tertiary = rgba(133724ff)

$image = /home/mohiitp/pix/car.png
$on_tertiary_container = rgba(c4eccfff)

$image = /home/mohiitp/pix/car.png
$on_tertiary_fixed = rgba(002110ff)

$image = /home/mohiitp/pix/car.png
$on_tertiary_fixed_variant = rgba(2b4e39ff)

$image = /home/mohiitp/pix/car.png
$outline = rgba(969080ff)

$image = /home/mohiitp/pix/car.png
$outline_variant = rgba(4a4739ff)

$image = /home/mohiitp/pix/car.png
$primary = rgba(d9c76fff)

$image = /home/mohiitp/pix/car.png
$primary_container = rgba(524600ff)

$image = /home/mohiitp/pix/car.png
$primary_fixed = rgba(f6e388ff)

$image = /home/mohiitp/pix/car.png
$primary_fixed_dim = rgba(d9c76fff)

$image = /home/mohiitp/pix/car.png
$scrim = rgba(000000ff)

$image = /home/mohiitp/pix/car.png
$secondary = rgba(d0c7a2ff)

$image = /home/mohiitp/pix/car.png
$secondary_container = rgba(4d472bff)

$image = /home/mohiitp/pix/car.png
$secondary_fixed = rgba(ede2bcff)

$image = /home/mohiitp/pix/car.png
$secondary_fixed_dim = rgba(d0c7a2ff)

$image = /home/mohiitp/pix/car.png
$shadow = rgba(000000ff)

$image = /home/mohiitp/pix/car.png
$source_color = rgba(a19b88ff)

$image = /home/mohiitp/pix/car.png
$surface = rgba(15130bff)

$image = /home/mohiitp/pix/car.png
$surface_bright = rgba(3c3930ff)

$image = /home/mohiitp/pix/car.png
$surface_container = rgba(222017ff)

$image = /home/mohiitp/pix/car.png
$surface_container_high = rgba(2c2a21ff)

$image = /home/mohiitp/pix/car.png
$surface_container_highest = rgba(37352bff)

$image = /home/mohiitp/pix/car.png
$surface_container_low = rgba(1e1c13ff)

$image = /home/mohiitp/pix/car.png
$surface_container_lowest = rgba(100e07ff)

$image = /home/mohiitp/pix/car.png
$surface_dim = rgba(15130bff)

$image = /home/mohiitp/pix/car.png
$surface_tint = rgba(d9c76fff)

$image = /home/mohiitp/pix/car.png
$surface_variant = rgba(4a4739ff)

$image = /home/mohiitp/pix/car.png
$tertiary = rgba(a9d0b4ff)

$image = /home/mohiitp/pix/car.png
$tertiary_container = rgba(2b4e39ff)

$image = /home/mohiitp/pix/car.png
$tertiary_fixed = rgba(c4eccfff)

$image = /home/mohiitp/pix/car.png
$tertiary_fixed_dim = rgba(a9d0b4ff)

