
$image = /home/mohiitp/pix/dragon.jpg
$background = rgba(16130bff)

$image = /home/mohiitp/pix/dragon.jpg
$error = rgba(ffb4abff)

$image = /home/mohiitp/pix/dragon.jpg
$error_container = rgba(93000aff)

$image = /home/mohiitp/pix/dragon.jpg
$inverse_on_surface = rgba(343027ff)

$image = /home/mohiitp/pix/dragon.jpg
$inverse_primary = rgba(745b0bff)

$image = /home/mohiitp/pix/dragon.jpg
$inverse_surface = rgba(eae1d4ff)

$image = /home/mohiitp/pix/dragon.jpg
$on_background = rgba(eae1d4ff)

$image = /home/mohiitp/pix/dragon.jpg
$on_error = rgba(690005ff)

$image = /home/mohiitp/pix/dragon.jpg
$on_error_container = rgba(ffdad6ff)

$image = /home/mohiitp/pix/dragon.jpg
$on_primary = rgba(3e2e00ff)

$image = /home/mohiitp/pix/dragon.jpg
$on_primary_container = rgba(ffdf92ff)

$image = /home/mohiitp/pix/dragon.jpg
$on_primary_fixed = rgba(241a00ff)

$image = /home/mohiitp/pix/dragon.jpg
$on_primary_fixed_variant = rgba(594400ff)

$image = /home/mohiitp/pix/dragon.jpg
$on_secondary = rgba(392f15ff)

$image = /home/mohiitp/pix/dragon.jpg
$on_secondary_container = rgba(f3e1bbff)

$image = /home/mohiitp/pix/dragon.jpg
$on_secondary_fixed = rgba(231a04ff)

$image = /home/mohiitp/pix/dragon.jpg
$on_secondary_fixed_variant = rgba(51462aff)

$image = /home/mohiitp/pix/dragon.jpg
$on_surface = rgba(eae1d4ff)

$image = /home/mohiitp/pix/dragon.jpg
$on_surface_variant = rgba(cfc5b4ff)

$image = /home/mohiitp/pix/dragon.jpg
$on_tertiary = rgba(1a361eff)

$image = /home/mohiitp/pix/dragon.jpg
$on_tertiary_container = rgba(c9ebc7ff)

$image = /home/mohiitp/pix/dragon.jpg
$on_tertiary_fixed = rgba(05210bff)

$image = /home/mohiitp/pix/dragon.jpg
$on_tertiary_fixed_variant = rgba(314d33ff)

$image = /home/mohiitp/pix/dragon.jpg
$outline = rgba(989080ff)

$image = /home/mohiitp/pix/dragon.jpg
$outline_variant = rgba(4c4639ff)

$image = /home/mohiitp/pix/dragon.jpg
$primary = rgba(e5c36cff)

$image = /home/mohiitp/pix/dragon.jpg
$primary_container = rgba(594400ff)

$image = /home/mohiitp/pix/dragon.jpg
$primary_fixed = rgba(ffdf92ff)

$image = /home/mohiitp/pix/dragon.jpg
$primary_fixed_dim = rgba(e5c36cff)

$image = /home/mohiitp/pix/dragon.jpg
$scrim = rgba(000000ff)

$image = /home/mohiitp/pix/dragon.jpg
$secondary = rgba(d6c5a0ff)

$image = /home/mohiitp/pix/dragon.jpg
$secondary_container = rgba(51462aff)

$image = /home/mohiitp/pix/dragon.jpg
$secondary_fixed = rgba(f3e1bbff)

$image = /home/mohiitp/pix/dragon.jpg
$secondary_fixed_dim = rgba(d6c5a0ff)

$image = /home/mohiitp/pix/dragon.jpg
$shadow = rgba(000000ff)

$image = /home/mohiitp/pix/dragon.jpg
$source_color = rgba(7a6a43ff)

$image = /home/mohiitp/pix/dragon.jpg
$surface = rgba(16130bff)

$image = /home/mohiitp/pix/dragon.jpg
$surface_bright = rgba(3d392fff)

$image = /home/mohiitp/pix/dragon.jpg
$surface_container = rgba(231f17ff)

$image = /home/mohiitp/pix/dragon.jpg
$surface_container_high = rgba(2e2a21ff)

$image = /home/mohiitp/pix/dragon.jpg
$surface_container_highest = rgba(39342bff)

$image = /home/mohiitp/pix/dragon.jpg
$surface_container_low = rgba(1f1b13ff)

$image = /home/mohiitp/pix/dragon.jpg
$surface_container_lowest = rgba(110e07ff)

$image = /home/mohiitp/pix/dragon.jpg
$surface_dim = rgba(16130bff)

$image = /home/mohiitp/pix/dragon.jpg
$surface_tint = rgba(e5c36cff)

$image = /home/mohiitp/pix/dragon.jpg
$surface_variant = rgba(4c4639ff)

$image = /home/mohiitp/pix/dragon.jpg
$tertiary = rgba(aecfacff)

$image = /home/mohiitp/pix/dragon.jpg
$tertiary_container = rgba(314d33ff)

$image = /home/mohiitp/pix/dragon.jpg
$tertiary_fixed = rgba(c9ebc7ff)

$image = /home/mohiitp/pix/dragon.jpg
$tertiary_fixed_dim = rgba(aecfacff)

