source = colors.conf

source = ./modules/monitor.conf
source = ./modules/env.conf
source = ./modules/autostart.conf
source = ./modules/keybinding.conf 
source = ./modules/animation.conf
source = ./modules/window_rule.conf
source = ./modules/looknfeel.conf
