background {
    path = /home/mohiitp/pix/car.png 
    blur_passes = 2
    blur_size = 5
}

input-field {
    size = 250, 50
    position = 0, -80
    dots_center = true
    fade_on_empty = false
    placeholder_text = Enter Password...
}

label {
    text = cmd[update:1000] echo "$(date +'%I:%M %p')"  # 12-hour format with AM/PM
    font_family =  CommitMono Nerd Font                     # Your requested font 
    font_size = 80                                      # Increased from 50
    position = 0, 100                                   # Moved up slightly to clear the input field
    halign = center
    valign = center
}
