background {
    path = /home/mohiitp/pix/cloud.png 
    blur_passes = 2
    blur_size = 5
}

input-field {
    size = 250, 50
    position = 0, -80
    dots_center = true
    fade_on_empty = false
    placeholder_text = Enter Password...
}

label {
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    position = 0, 80
    font_size = 50
}
