#! /bin/sh

picom & 
/home/mohit_iitp/.config/polybar/launch.sh &
/home/mohit_iitp/.local/bin/wall &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d u i o p 
bspc monitor DP-0 -d j k l n m  
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a com.mitchellh.ghostty desktop='u' follow=on
bspc rule -a Google-chrome desktop='o' follow=on
bspc rule -a Spotify desktop='m' follow=off
bspc rule -a discord desktop='l' follow=off

# Enable focus follows mouse
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
